// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhantasyBot.DataAccess.Database.Contexts;

namespace PhantasyBot.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PhantasyBot.DataAccess.Database.Entities.CommandLogEntity", b =>
                {
                    b.Property<long>("CommandLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandName")
                        .IsRequired();

                    b.Property<string>("CommandParams");

                    b.Property<DateTime>("CommandTimestamp");

                    b.Property<string>("UserDisplayName")
                        .IsRequired();

                    b.Property<ulong>("UserId");

                    b.HasKey("CommandLogId");

                    b.ToTable("CommandLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
